// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/nalawade41/secret-server/db"
	"github.com/nalawade41/secret-server/internal/secret"
	"github.com/nalawade41/secret-server/internal/secret/handler"
)

// Injectors from wire.go:

func InitializeRouteProvider(dbConnection db.DynamoDBAPI, tableName string) *handler.SecretManagerHandler {
	secretManagerRepository := secret.NewSecretManagerRepository(dbConnection, tableName)
	realEncryptor := secret.NewEncryptor()
	secretManagerUseCase := secret.NewSecretManagerUseCase(secretManagerRepository, realEncryptor)
	secretManagerHandler := secret.NewSecretManagerHandler(secretManagerUseCase)
	return secretManagerHandler
}
