// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/nalawade41/secret-server/internal/secret"
	"github.com/nalawade41/secret-server/internal/secret/handler"
)

// Injectors from wire.go:

func InitializeRouteProvider(dbConnection *dynamodb.Client, tableName string) *handler.SecretManagerHandler {
	secretManagerRepository := secret.NewSecretManagerRepository(dbConnection, tableName)
	secretManagerUseCase := secret.NewSecretManagerUseCase(secretManagerRepository)
	secretManagerHandler := secret.NewSecretManagerHandler(secretManagerUseCase)
	return secretManagerHandler
}
