// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nalawade41/secret-server/internal/domain (interfaces: Encryptor)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncryptor is a mock of Encryptor interface.
type MockEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorMockRecorder
}

// MockEncryptorMockRecorder is the mock recorder for MockEncryptor.
type MockEncryptorMockRecorder struct {
	mock *MockEncryptor
}

// NewMockEncryptor creates a new mock instance.
func NewMockEncryptor(ctrl *gomock.Controller) *MockEncryptor {
	mock := &MockEncryptor{ctrl: ctrl}
	mock.recorder = &MockEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptor) EXPECT() *MockEncryptorMockRecorder {
	return m.recorder
}

// EncryptMessage mocks base method.
func (m *MockEncryptor) EncryptMessage(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptMessage", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptMessage indicates an expected call of EncryptMessage.
func (mr *MockEncryptorMockRecorder) EncryptMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptMessage", reflect.TypeOf((*MockEncryptor)(nil).EncryptMessage), arg0, arg1)
}

// GenerateSHA256Hash mocks base method.
func (m *MockEncryptor) GenerateSHA256Hash(arg0 ...string) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateSHA256Hash", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSHA256Hash indicates an expected call of GenerateSHA256Hash.
func (mr *MockEncryptorMockRecorder) GenerateSHA256Hash(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSHA256Hash", reflect.TypeOf((*MockEncryptor)(nil).GenerateSHA256Hash), arg0...)
}
