// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nalawade41/secret-server/internal/domain (interfaces: SecretUseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nalawade41/secret-server/internal/domain"
)

// MockSecretUseCase is a mock of SecretUseCase interface.
type MockSecretUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSecretUseCaseMockRecorder
}

// MockSecretUseCaseMockRecorder is the mock recorder for MockSecretUseCase.
type MockSecretUseCaseMockRecorder struct {
	mock *MockSecretUseCase
}

// NewMockSecretUseCase creates a new mock instance.
func NewMockSecretUseCase(ctrl *gomock.Controller) *MockSecretUseCase {
	mock := &MockSecretUseCase{ctrl: ctrl}
	mock.recorder = &MockSecretUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretUseCase) EXPECT() *MockSecretUseCaseMockRecorder {
	return m.recorder
}

// CreateSecretMessage mocks base method.
func (m *MockSecretUseCase) CreateSecretMessage(arg0 context.Context, arg1 domain.Secret) (domain.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecretMessage", arg0, arg1)
	ret0, _ := ret[0].(domain.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecretMessage indicates an expected call of CreateSecretMessage.
func (mr *MockSecretUseCaseMockRecorder) CreateSecretMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecretMessage", reflect.TypeOf((*MockSecretUseCase)(nil).CreateSecretMessage), arg0, arg1)
}

// GetSecretMessage mocks base method.
func (m *MockSecretUseCase) GetSecretMessage(arg0 context.Context, arg1 string) (domain.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretMessage", arg0, arg1)
	ret0, _ := ret[0].(domain.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretMessage indicates an expected call of GetSecretMessage.
func (mr *MockSecretUseCaseMockRecorder) GetSecretMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretMessage", reflect.TypeOf((*MockSecretUseCase)(nil).GetSecretMessage), arg0, arg1)
}
